In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

print("All libraries loaded successfully!")

All libraries loaded successfully!

In [2]:
import pandas as pd 
df = pd.read_csv('big_startup_secsees_dataset.csv')
df.head()

,permalink,name,homepage_url,category_list,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,first_funding_at,last_funding_at
0,/organization/-fame,#fame,http://livfame.com,Media,10000000,operating,IND,16,Mumbai,Mumbai,1,NaN,2015-01-05,2015-01-05
1,/organization/-qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,700000,operating,USA,DE,DE - Other,Delaware City,2,2014-09-04,2014-03-01,2014-10-14
2,/organization/-the-one-of-them-inc-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,3406878,operating,NaN,NaN,NaN,NaN,1,NaN,2014-01-30,2014-01-30
3,/organization/0-6-com,0-6.com,http://www.0-6.com,Curated Web,2000000,operating,CHN,22,Beijing,Beijing,1,2007-01-01,2008-03-19,2008-03-19
4,/organization/004-technologies,004 Technologies,http://004gmbh.de/en/004-interact,Software,-,operating,USA,IL,"Springfield, Illinois",Champaign,1,2010-01-01,2014-07-24,2014-07-24

In [3]:
df.columns

Index(['permalink', 'name', 'homepage_url', 'category_list',
       'funding_total_usd', 'status', 'country_code', 'state_code', 'region',
       'city', 'funding_rounds', 'founded_at', 'first_funding_at',
       'last_funding_at'],
      dtype='object')

In [4]:
print("Shape of dataset",df.shape)
print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])

Shape of dataset (66368, 14)
Total Rows: 66368
Total Columns: 14

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66368 entries, 0 to 66367
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   permalink          66368 non-null  object
 1   name               66367 non-null  object
 2   homepage_url       61310 non-null  object
 3   category_list      63220 non-null  object
 4   funding_total_usd  66368 non-null  object
 5   status             66368 non-null  object
 6   country_code       59410 non-null  object
 7   state_code         57821 non-null  object
 8   region             58338 non-null  object
 9   city               58340 non-null  object
 10  funding_rounds     66368 non-null  int64
 11  founded_at         51147 non-null  object
 12  first_funding_at   66344 non-null  object
 13  last_funding_at    66368 non-null  object
dtypes: int64(1), object(13)
memory usage: 7.1+ MB

In [6]:
df.describe()

       funding_rounds
count    66368.000000
mean         1.732522
std          1.360251
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max         19.000000

In [7]:
df['status'].value_counts()

status
operating    53034
closed        6238
acquired      5549
ipo           1547
Name: count, dtype: int64

In [8]:
df.dtypes

permalink            object
name                 object
homepage_url         object
category_list        object
funding_total_usd    object
status               object
country_code         object
state_code           object
region               object
city                 object
funding_rounds        int64
founded_at           object
first_funding_at     object
last_funding_at      object
dtype: object

In [9]:
print("Missing Values in each column:")
print(df.isnull().sum())

Missing Values in each column:
permalink                0
name                     1
homepage_url          5058
category_list         3148
funding_total_usd        0
status                   0
country_code          6958
state_code            8547
region                8030
city                  8028
funding_rounds           0
founded_at           15221
first_funding_at        24
last_funding_at          0
dtype: int64

In [10]:
df = df.drop(columns=['permalink', 'homepage_url', 'name', 'state_code'])
print("Irrelevant columns dropped!")

Irrelevant columns dropped!

In [11]:
df['funding_total_usd'] = pd.to_numeric(df['funding_total_usd'].replace('-', np.nan), errors='coerce')

df['category_list'] = df['category_list'].fillna(df['category_list'].mode()[0])
df['country_code'] = df['country_code'].fillna(df['country_code'].mode()[0])
df['region'] = df['region'].fillna(df['region'].mode()[0])
df['city'] = df['city'].fillna(df['city'].mode()[0])

df['funding_total_usd'] = df['funding_total_usd'].fillna(df['funding_total_usd'].median())

df = df.dropna(subset=['founded_at', 'first_funding_at'])

print("All missing values handled!")

All missing values handled!

In [12]:
print("Remaining missing values:")
print(df.isnull().sum())
print("\nNew shape of dataset:", df.shape)

Remaining missing values:
category_list        0
funding_total_usd    0
status               0
country_code         0
region               0
city                 0
funding_rounds       0
founded_at           0
first_funding_at     0
last_funding_at      0
dtype: int64

New shape of dataset: (51126, 10)

In [13]:
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 22

In [14]:
df = df.drop_duplicates()
print("Duplicates removed!")
print("New shape of dataset:", df.shape)

Duplicates removed!
New shape of dataset: (51104, 10)

In [15]:
print("Remaining duplicates:", df.duplicated().sum())

Remaining duplicates: 0

In [16]:
print(df.columns)

Index(['category_list', 'funding_total_usd', 'status', 'country_code',
       'region', 'city', 'funding_rounds', 'founded_at', 'first_funding_at',
       'last_funding_at'],
      dtype='object')

In [17]:
df = df.rename(columns={
    'category_list': 'industry',
    'funding_total_usd': 'total_funding',
    'country_code': 'country',
    'state_code': 'state',
    'founded_at': 'founded_date',
    'first_funding_at': 'first_funding_date',
    'last_funding_at': 'last_funding_date',
})
print("Columns renamed successfully!")
print(df.columns)

Columns renamed successfully!
Index(['industry', 'total_funding', 'status', 'country', 'region', 'city',
       'funding_rounds', 'founded_date', 'first_funding_date',
       'last_funding_date'],
      dtype='object')

In [18]:
df.head()

,industry,total_funding,status,country,region,city,funding_rounds,founded_date,first_funding_date,last_funding_date
1,Application Platforms|Real Time|Social Network...,700000.0,operating,USA,DE - Other,Delaware City,2,2014-09-04,2014-03-01,2014-10-14
3,Curated Web,2000000.0,operating,CHN,Beijing,Beijing,1,2007-01-01,2008-03-19,2008-03-19
4,Software,2000000.0,operating,USA,"Springfield, Illinois",Champaign,1,2010-01-01,2014-07-24,2014-07-24
6,Biotechnology,762851.0,operating,CAN,Vancouver,Vancouver,2,1997-01-01,2009-09-11,2009-12-21
7,Analytics,33600000.0,operating,USA,SF Bay Area,Mountain View,4,2011-01-01,2013-01-03,2015-11-09

In [19]:
df.tail()

,industry,total_funding,status,country,region,city,funding_rounds,founded_date,first_funding_date,last_funding_date
66361,Biotechnology,2686600.0,operating,AUT,Vienna,Gerasdorf Bei Wien,1,2007-01-01,2013-01-29,2013-01-29
66362,Analytics|Android|Developer APIs|Education|Gam...,1120000.0,operating,GBR,London,London,3,2014-01-28,2014-03-24,2015-02-25
66364,Advertising|Mobile|Web Development|Wireless,114304.0,operating,HRV,Split,Split,4,2012-05-13,2011-11-01,2014-03-01
66365,Software,2000000.0,operating,USA,SF Bay Area,San Francisco,1,2011-01-01,2014-08-01,2014-08-01
66366,Consumer Electronics|Internet of Things|Teleco...,18192.0,operating,USA,SF Bay Area,San Francisco,1,2014-01-01,2015-01-01,2015-01-01

In [21]:
print("FINAL CHECK")
print("\nShape:", df.shape)
print("\nMissing Values:")
print(df.isnull().sum())
print("\nDuplicates:", df.duplicated().sum())
print("\nData Types:")
print(df.dtypes)

FINAL CHECK

Shape: (51104, 10)

Missing Values:
industry              0
total_funding         0
status                0
country               0
region                0
city                  0
funding_rounds        0
founded_date          0
first_funding_date    0
last_funding_date     0
dtype: int64

Duplicates: 0

Data Types:
industry               object
total_funding         float64
status                 object
country                object
region                 object
city                   object
funding_rounds          int64
founded_date           object
first_funding_date     object
last_funding_date      object
dtype: object

In [22]:
df.to_csv('clean_startups.csv', index=False)
print("Clean dataset saved successfully!")

Clean dataset saved successfully!